// Public surface of the framework-agnostic core.
export * from './geo/types';
export { DEFAULT_MARGIN_MM, getPageDimensions, getPrintableArea, uniformMargins } from './geo/paper';
export { clipPolylineToRect, printableRect } from './geo/clip';
export { crossHatchFill, dotFill, filledPolygon, filledRect, hatchFill, rectOutline } from './scene/textures';
export { arcPoints, beadedPath, ladderPath, parallelPair, scatterFill, segment, wavyFill, wavyPath } from './scene/lines';
export { icon, ICON_KINDS } from './scene/icons';
export type { IconKind } from './scene/icons';
export { clipTextureToPolygon, clearTextureAroundLine, pointInPolygon, distPointToPolyline } from './scene/fill';
export { renderPdf, renderPdfPages } from './pdf/render';
export type { RenderOptions } from './pdf/render';
export { buildCalibrationScene } from './calibration';
export type { CalibrationParams } from './calibration';
export { basicTranslator } from './braille/translate';
export type { Translator } from './braille/translate';
export { decodeBrailleUnicode } from './braille/decode';
export { makeLiblouisTranslator } from './braille/liblouis';
export type { LiblouisGrade, LiblouisOptions, TranslateString } from './braille/liblouis';
export { collectLabelCandidates, placeLabels, buildLegendScenes, keyFor } from './label';
export { buildFurniture, scaleBarDistance } from './furniture';
export { simplify } from './geo/simplify';
export { buildTestSheets } from './testsheets';
export { buildDemoMap } from './demoMap';
export { generateMap, coverageBBox, renderedBBox, renderCalibration, renderTestSheets, renderDemoMap } from './pipeline';
export type { MapParams, MapResult, CoverageParams } from './pipeline';
export { styles, streetOverview } from './style/defaultStyle';
export { TACTILE_LINES, TACTILE_AREAS, MIN_LINE_WIDTH_MM } from './style/vocabulary';
export type { TactileLine, TactileLineName, LinePattern, TactileArea, TactileAreaName, AreaFill } from './style/vocabulary';
export type { StyleSpec } from './style/types';
